package jp.co.xq.service.sys.mapper;

import java.util.List;
import jp.co.xq.service.sys.model.SysUserQuestion;
import jp.co.xq.service.sys.model.SysUserQuestionExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SysUserQuestionMapper {
    long countByExample(SysUserQuestionExample example);

    int deleteByExample(SysUserQuestionExample example);

    int deleteByPrimaryKey(Long id);

    int insert(SysUserQuestion record);

    int insertSelective(SysUserQuestion record);

    List<SysUserQuestion> selectByExample(SysUserQuestionExample example);

    SysUserQuestion selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") SysUserQuestion record, @Param("example") SysUserQuestionExample example);

    int updateByExample(@Param("record") SysUserQuestion record, @Param("example") SysUserQuestionExample example);

    int updateByPrimaryKeySelective(SysUserQuestion record);

    int updateByPrimaryKey(SysUserQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_question
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SysUserQuestion> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_question
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SysUserQuestion> list, @Param("selective") SysUserQuestion.Column... selective);
}
